npm install gulp  --save-dev
npm install browser-sync --save-dev
npm install gulp-bump  --save-dev
npm install gulp-autoprefixer  --save-dev
npm install gulp-csslint --save-dev
npm install gulp-minify-css  --save-dev
npm install gulp-jshint  --save-dev
npm install gulp-concat  --save-dev
npm install gulp-uglify  --save-dev
npm install gulp-imagemin  --save-dev
npm install gulp-notify  --save-dev
npm install gulp-rename  --save-dev
npm install gulp-cache  --save-dev
npm install gulp-jsbeautifier --save-dev
npm install gulp-less --save-dev
npm install del --save-dev
npm install gulp-header --save-dev
npm install gulp-load-plugins --save-dev 
npm install gulp-uncss --save-dev

